# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 05:53
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('p_img', models.FileField(null=True, upload_to='')),
                ('p_upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('p_name', models.TextField()),
                ('p_price', models.IntegerField()),
                ('p_desc', models.TextField()),
                ('p_rating', models.IntegerField(null=True)),
                ('p_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
