# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_new_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_product',
            name='image',
        ),
        migrations.AlterField(
            model_name='new_product',
            name='p_img',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
