# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180316_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_product',
            name='p_img',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='new_product',
            name='p_upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, max_length=20),
        ),
    ]
